; pio run -t upload
[platformio]
default_envs = node1_main_ota, node2_demo_ota

[env]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

; sudo chmod 666 /dev/ttyACM0
; pio run -e esp32_cable -t upload
[env:esp32_cable]
upload_protocol = esptool

; pio run -e node1_main_ota -t upload
[env:node1_main_ota]
upload_protocol = espota
upload_port = 192.168.0.202
upload_flags =
    --host_port=8266

; pio run -e node2_demo_ota -t upload
[env:node2_demo_ota]
upload_protocol = espota
upload_port = 192.168.0.203
upload_flags =
    --host_port=8267